// app/blog/src/components/modules/Navbar/NavBar.vue
<script setup lang="ts">
import { computed } from "vue";
import { tvButton } from "@styles/tv";
import NavStickyWrapper from "./NavStickyWrapper.vue";
import MobileMenu from "./MobileMenu.vue";
import MingcuteSearch3Line from "~icons/mingcute/search-3-line";
import { type NavMenu, navMenu } from "@configs/navbar";
import { siteConfig } from "@configs/site";
import ColorSelectPopover from "./ColorSelect/ColorSelectPopover.vue";

const props = defineProps<{
  navStats?: NavMenu | string;
}>();

const highlight = computed<number>(() => {
  if (props.navStats === undefined) return navMenu.length - 1;
  if (typeof props.navStats === "string")
    return navMenu.findIndex((item) => item.text === props.navStats);
  return navMenu.findIndex(
    (item) => item.text === (props.navStats as NavMenu).text,
  );
});
</script>

<template>
  <NavStickyWrapper>
    <div
      class="mx-auto grid size-full grid-cols-[1fr_auto_1fr] grid-rows-1 content-center items-center px-3 py-2 sm:px-4"
    >
      <div class="h-8 justify-self-start md:hidden"><MobileMenu /></div>
      <div class="justify-self-center md:justify-self-start">
        <a class="flex items-center text-xl" href="/">
          <slot />
          <span class="ml-3 hidden md:inline">{{ siteConfig.title }}</span>
        </a>
      </div>
      <div
        class="hidden h-full items-center space-x-1 justify-self-center md:flex"
      >
        <a
          v-for="(item, index) of navMenu"
          :key="item.text"
          :href="item.link"
          class="flex h-full w-20 font-medium center"
          :class="[
            highlight === index ? 'text-primary' : 'text-heading',
            tvButton(),
          ]"
        >
          <span
            class="z-1 inline-flex select-none items-center gap-1 self-center align-middle"
          >
            <component
              :is="item.vueIcon"
              v-if="highlight === index"
              class="h-5 w-5"
              style="view-transition-name: nav-item-icon"
            />
            <span :style="`view-transition-name: nav-item-text-` + item.text">
              {{ item.text }}
            </span>
          </span>
        </a>
      </div>
      <div class="flex h-fit gap-4 justify-self-end">
        <ColorSelectPopover />
        <a href="/search" aria-label="Search Button" class="size-6">
          <MingcuteSearch3Line class="size-6" />
        </a>
      </div>
    </div>
  </NavStickyWrapper>
</template>

// app/blog/src/components/modules/Navbar/NavBar.tsx
import { useEffect, useRef, useState, useMemo } from "react";
import remToPixel from "@utils/remToPixel";
import { tvButton } from "@styles/tv";
import { type NavMenu, navMenu } from "@configs/navbar";
import { siteConfig } from "@configs/site";
import MingcuteSearch3Line from "~icons/mingcute/search-3-line";
import NavbarMobile from "./NavBarMobile";

const DEFAULT_NAV_TOP_MARGIN = 1; // in rem

interface NavbarWrapperProps {
  children: React.ReactNode;
}

const NavbarWrapper: React.FC<NavbarWrapperProps> = ({ children }) => {
  const navRef = useRef<HTMLElement>(null);
  const [height, setHeight] = useState(0);
  const [scrollY, setScrollY] = useState(0);

  const isFixed = scrollY >= remToPixel(DEFAULT_NAV_TOP_MARGIN);

  // Handle scroll events
  useEffect(() => {
    const handleScroll = () => {
      setScrollY(window.scrollY);
    };
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  // Update element height
  useEffect(() => {
    if (navRef.current) {
      const resizeObserver = new ResizeObserver((entries) => {
        for (const entry of entries) {
          setHeight(entry.contentRect.height);
        }
      });
      resizeObserver.observe(navRef.current);
      return () => resizeObserver.disconnect();
    }
  }, []);

  // Set CSS variables
  useEffect(() => {
    document.documentElement.style.setProperty(
      "--navbar-height",
      `${height}px`,
    );
  }, [height]);

  useEffect(() => {
    document.documentElement.style.setProperty(
      "--navbar-top-margin",
      isFixed ? "0rem" : `${DEFAULT_NAV_TOP_MARGIN}rem`,
    );
  }, [isFixed]);

  return (
    <nav ref={navRef} className="sticky top-0 z-20 h-16 min-h-16 w-full">
      <div
        className={`absolute inset-y-0 left-1/2 h-full -translate-x-1/2 transform-gpu text-heading shadow backdrop-blur-lg ${isFixed ? "w-screen" : "w-full"} ${isFixed ? "bg-card/80" : "bg-card"} ${isFixed ? "rounded-none" : "rounded-card"} ${isFixed ? "transition-expand" : "transition-shrink"} `}
        style={{ viewTransitionName: "navbar" }}
      >
        {children}
      </div>
    </nav>
  );
};

interface NavbarProps {
  navStats?: NavMenu | string;
  children?: React.ReactNode;
}

const Navbar: React.FC<NavbarProps> = ({ navStats, children }) => {
  const highlight = useMemo(() => {
    if (navStats === undefined) return navMenu.length - 1;
    if (typeof navStats === "string")
      return navMenu.findIndex((item) => item.text === navStats);
    return navMenu.findIndex(
      (item) => item.text === (navStats as NavMenu).text,
    );
  }, [navStats]);

  return (
    <NavbarWrapper>
      <div className="mx-auto grid size-full grid-cols-[1fr_auto_1fr] grid-rows-1 content-center items-center px-3 py-2 sm:px-4">
        <div className="h-8 justify-self-start md:hidden">
          <NavbarMobile />
        </div>
        <div className="justify-self-center md:justify-self-start">
          <a className="flex items-center text-xl" href="/">
            {children}
            <span className="ml-3 hidden md:inline">{siteConfig.title}</span>
          </a>
        </div>
        <div className="hidden h-full items-center space-x-1 justify-self-center md:flex">
          {navMenu.map((item, index) => {
            const Icon = item.iconSvg; // Assuming the icon prop name changed from vueIcon to icon
            return (
              <a
                key={item.text}
                href={item.link}
                className={`flex h-full w-20 font-medium center ${
                  highlight === index ? "text-primary" : "text-heading"
                } ${tvButton()}`}
              >
                <span className="z-1 inline-flex select-none items-center gap-1 self-center align-middle">
                  {highlight === index && Icon && <Icon />}
                  <span
                    style={{
                      viewTransitionName: `nav-item-text-${item.text}`,
                    }}
                  >
                    {item.text}
                  </span>
                </span>
              </a>
            );
          })}
        </div>
        <div className="flex h-fit gap-4 justify-self-end">
          {/* <ColorSelectPopover /> */}
          <a href="/search" aria-label="Search Button" className="size-6">
            <MingcuteSearch3Line className="size-6" />
          </a>
        </div>
      </div>
    </NavbarWrapper>
  );
};

export default Navbar;
