// app/blog/src/components/modules/ArticleCard/CommentCard.tsx
import React, { useEffect, useRef } from "react";
import {
  type WalineInstance,
  type WalineInitOptions,
  init,
} from "@waline/client";

import "@waline/client/style";

export type WalineOptions = Omit<WalineInitOptions, "el"> & { path: string };

const Waline = (props: WalineOptions) => {
  const config: WalineOptions = {
    dark: "auto",
    lang: "zh-CN",
    search: false,
    emoji: false,
    // @ts-expect-error waline types are not updated
    reaction: false,
    requiredMeta: ["nick", "mail"],
    ...props,
  };
  const walineInstanceRef = useRef<WalineInstance | null>(null);
  const containerRef = React.createRef<HTMLDivElement>();

  useEffect(() => {
    walineInstanceRef.current = init({
      ...config,
      path: window.location.pathname.endsWith("/")
        ? window.location.pathname.slice(0, -1)
        : window.location.pathname,
      el: containerRef.current,
    });

    return () => walineInstanceRef.current?.destroy();
  }, []);

  useEffect(() => {
    document.addEventListener("astro:before-preparation", () => {
      walineInstanceRef.current?.destroy();
    });
  }, []);

  useEffect(() => {
    walineInstanceRef.current?.update(config);
  }, [config]);

  return <div ref={containerRef} />;
};

export { Waline as default };

// src/components/elements/CommentCard.vue
<script setup lang="ts">
// @ts-expect-error don't get types...
import { Waline } from "@waline/client/component";
import { ref, onMounted, onUnmounted } from "vue";
defineProps<{
  serverUrl: string;
}>();

import "@waline/client/style";

const path = ref("");

const updatePath = () => {
  path.value = window.location.pathname;
};

onMounted(() => {
  updatePath();
  window.addEventListener("popstate", updatePath);
});
onUnmounted(() => {
  window.removeEventListener("popstate", updatePath);
});
</script>
<template>
  <div class="bg-card rounded-xl shadow-lg p-2">
    <Waline
      :server-u-r-l="serverUrl"
      :path
      dark="auto"
      lang="zh-CN"
      :search="false"
      :emoji="false"
      :required-meta="['nick', 'mail']"
    />
  </div>
</template>

<style>
.wl-count {
  color: var(--waline-color);
}
</style>
